function createPublicApiRouteContext(context) {
  return {
    app: context.app,
    models: context.models,
    runtime: context.runtime,
    partyOwnerLeases: context.partyOwnerLeases,
    bcrypt: context.bcrypt,
    crypto: context.crypto,
    fs: context.fs,
    os: context.os,
    path: context.path,
    spawn: context.spawn,
    multer: context.multer,
    ffmpegPath: context.ffmpegPath,
    packageJson: context.packageJson,
    generateDeleteCode: context.generateDeleteCode,
    getCookieValue: context.getCookieValue,
    assertAuthThrottle: context.assertAuthThrottle,
    exportGameModesToJson: context.exportGameModesToJson,
    exportGamePacksToJson: context.exportGamePacksToJson,
    exportGameRolesToJson: context.exportGameRolesToJson,
    exportGameRulesToJson: context.exportGameRulesToJson,
    exportAchievementsToJson: context.exportAchievementsToJson,
    exportOlingConsumablesToJson: context.exportOlingConsumablesToJson,
    serializeOeImagesForPackJson: context.serializeOeImagesForPackJson,
    getPublicSiteUrl: context.getPublicSiteUrl,
    sendEmailChangeEmail: context.sendEmailChangeEmail,
    sendPasswordResetEmail: context.sendPasswordResetEmail,
    sendVerificationEmail: context.sendVerificationEmail,
    serializeOpalTransactions: context.serializeOpalTransactions,
    serializeOpalWallet: context.serializeOpalWallet,
    grantShopItemsToAccount: context.grantShopItemsToAccount,
    ONLINE_GAMEMODE_MAX_PLAYERS: context.ONLINE_GAMEMODE_MAX_PLAYERS,
    PUBLIC_DIRECTORY: context.PUBLIC_DIRECTORY,
    WEBSITE_CACHE_VERSION: context.WEBSITE_CACHE_VERSION,
    isProduction: context.isProduction,
    OE_PANEL_ROLES: context.OE_PANEL_ROLES,
    SYSTEM_FEATURE_FLAGS: context.SYSTEM_FEATURE_FLAGS,
    createAdminLog: context.createAdminLog,
    formatSystemConfigDate: context.formatSystemConfigDate,
    serializeAdminLog: context.serializeAdminLog,
    normalizeSocialPlatforms: context.normalizeSocialPlatforms,
    serializeSocialContentItem: context.serializeSocialContentItem,
    OE_PANEL_EXPORT_UPLOAD: context.OE_PANEL_EXPORT_UPLOAD,
    OE_PANEL_SVG_UPLOAD: context.OE_PANEL_SVG_UPLOAD,
    clampNumber: context.clampNumber,
    escapeFfmpegText: context.escapeFfmpegText,
    runFfmpeg: context.runFfmpeg,
    accountSaltRounds: context.accountSaltRounds,
    defaultOeIcon: context.defaultOeIcon,
    oeIconPattern: context.oeIconPattern,
    OverexposurePost: context.OverexposurePost,
    SocialContentItem: context.SocialContentItem,
    EmailTemplate: context.EmailTemplate,
    Report: context.Report,
    Account: context.Account,
    Product: context.Product,
    ShopConfig: context.ShopConfig,
    OlingState: context.OlingState,
    OlingBattleMatch: context.OlingBattleMatch,
    OlingBattleEvent: context.OlingBattleEvent,
    Achievement: context.Achievement,
    GamePack: context.GamePack,
    GameRole: context.GameRole,
    GameRule: context.GameRule,
    GameMode: context.GameMode,
    GamemodeSettingsAlert: context.GamemodeSettingsAlert,
    OeCustomisation: context.OeCustomisation,
    SystemConfig: context.SystemConfig,
    AdminLog: context.AdminLog,
    accountsConnection: context.accountsConnection,
    olingsConnection: context.olingsConnection,
    partyGamesConnection: context.partyGamesConnection,
    oeCustomisationConnection: context.oeCustomisationConnection,
    shopConnection: context.shopConnection,
    moderationConnection: context.moderationConnection,
    socialConnection: context.socialConnection,
    emailConnection: context.emailConnection,
    waitingRoomSchema: context.waitingRoomSchema,
    partyGameTruthOrDareSchema: context.partyGameTruthOrDareSchema,
    partyGameParanoiaSchema: context.partyGameParanoiaSchema,
    partyGameNeverHaveIEverSchema: context.partyGameNeverHaveIEverSchema,
    partyGameMostLikelyToSchema: context.partyGameMostLikelyToSchema,
    partyGameImposterSchema: context.partyGameImposterSchema,
    partyGameWouldYouRatherSchema: context.partyGameWouldYouRatherSchema,
    partyGameMafiaSchema: context.partyGameMafiaSchema,
    partyGameChatLogSchema: context.partyGameChatLogSchema,
    archivedRoomSchema: context.archivedRoomSchema,
    buildLoginRedirect: context.buildLoginRedirect,
    buildOverexposurePostReport: context.buildOverexposurePostReport,
    buildSocialUsername: context.buildSocialUsername,
    checkAuthThrottle: context.checkAuthThrottle,
    clearExpiredAccountSessions: context.clearExpiredAccountSessions,
    createAppleClientSecret: context.createAppleClientSecret,
    createEmailChangeToken: context.createEmailChangeToken,
    createEmailVerificationToken: context.createEmailVerificationToken,
    createGamePackCreatePayload: context.createGamePackCreatePayload,
    createGamePackUpdatePayload: context.createGamePackUpdatePayload,
    createGameRoleUpdatePayload: context.createGameRoleUpdatePayload,
    createGameRuleUpdatePayload: context.createGameRuleUpdatePayload,
    createGamemodeSettingsAlert: context.createGamemodeSettingsAlert,
    createOAuthState: context.createOAuthState,
    createOeCustomisationImageCreatePayload:
      context.createOeCustomisationImageCreatePayload,
    createOeCustomisationImageUpdatePayload:
      context.createOeCustomisationImageUpdatePayload,
    createOeCustomisationPackCreatePayload:
      context.createOeCustomisationPackCreatePayload,
    createOeCustomisationPackUpdatePayload:
      context.createOeCustomisationPackUpdatePayload,
    createOverexposureAccountSummary: context.createOverexposureAccountSummary,
    createPasswordResetToken: context.createPasswordResetToken,
    createPkcePair: context.createPkcePair,
    createRoomIssueAlert: context.createRoomIssueAlert,
    createSignupLegalConsent: context.createSignupLegalConsent,
    createSessionToken: context.createSessionToken,
    createSocialAccount: context.createSocialAccount,
    decodeJwtPayload: context.decodeJwtPayload,
    establishAccountSession: context.establishAccountSession,
    fetchOAuthProfile: context.fetchOAuthProfile,
    fetchOAuthToken: context.fetchOAuthToken,
    findOrCreateSocialAccount: context.findOrCreateSocialAccount,
    findOverexposurePostForReport: context.findOverexposurePostForReport,
    formatCurrencyValue: context.formatCurrencyValue,
    formatOePanelDateTime: context.formatOePanelDateTime,
    formatPartyGameLabel: context.formatPartyGameLabel,
    formatReportLabel: context.formatReportLabel,
    formatRoomDetailValue: context.formatRoomDetailValue,
    formatRoundedDuration: context.formatRoundedDuration,
    getAccountRoleLabel: context.getAccountRoleLabel,
    getAccountLockoutSeconds: context.getAccountLockoutSeconds,
    getAppleDisplayName: context.getAppleDisplayName,
    getApplePrivateKey: context.getApplePrivateKey,
    getCurrentAccount: context.getCurrentAccount,
    getDateCountMap: context.getDateCountMap,
    getDefaultProductVariant: context.getDefaultProductVariant,
    getEmailVerifiedRedirect: context.getEmailVerifiedRedirect,
    getGamemodeSettingsAlertAction: context.getGamemodeSettingsAlertAction,
    getGamemodeSettingsAlertQuery: context.getGamemodeSettingsAlertQuery,
    getOAuthCallbackUrl: context.getOAuthCallbackUrl,
    getOAuthMode: context.getOAuthMode,
    getOAuthProviderConfig: context.getOAuthProviderConfig,
    getOeCustomisationFileExists: context.getOeCustomisationFileExists,
    getOeCustomisationIssues: context.getOeCustomisationIssues,
    getOePanelPostStatus: context.getOePanelPostStatus,
    getOePanelReportCount: context.getOePanelReportCount,
    getOePanelReportPost: context.getOePanelReportPost,
    getOePanelReportPostId: context.getOePanelReportPostId,
    getOverexposurePostedAt: context.getOverexposurePostedAt,
    getOverexposurePublicId: context.getOverexposurePublicId,
    getOverexposureReportSeverity: context.getOverexposureReportSeverity,
    getOverexposureTag: context.getOverexposureTag,
    getOverexposureTitle: context.getOverexposureTitle,
    getPartyGameRoomSources: context.getPartyGameRoomSources,
    getRequestBaseUrl: context.getRequestBaseUrl,
    getRequestedOeIcon: context.getRequestedOeIcon,
    getOeItemAccessState: context.getOeItemAccessState,
    getRoomErrorSummary: context.getRoomErrorSummary,
    getRoomInstruction: context.getRoomInstruction,
    getRoomIssueSeverity: context.getRoomIssueSeverity,
    getRoomPlayerCount: context.getRoomPlayerCount,
    getSafeReturnToPath: context.getSafeReturnToPath,
    getSafeSplashScreenPath: context.getSafeSplashScreenPath,
    getSignupContext: context.getSignupContext,
    getSignupSourceFromPath: context.getSignupSourceFromPath,
    getSupportedOAuthProvider: context.getSupportedOAuthProvider,
    hasOePanelPermission: context.hasOePanelPermission,
    hashEmailChangeToken: context.hashEmailChangeToken,
    hashEmailVerificationToken: context.hashEmailVerificationToken,
    hashOptionalRequestIp: context.hashOptionalRequestIp,
    hashPasswordResetToken: context.hashPasswordResetToken,
    hashSessionToken: context.hashSessionToken,
    isAccountEmailVerified: context.isAccountEmailVerified,
    isDefaultOeIcon: context.isDefaultOeIcon,
    linkOAuthProviderToAccount: context.linkOAuthProviderToAccount,
    mergeDateCountMaps: context.mergeDateCountMaps,
    normalizeAccountInput: context.normalizeAccountInput,
    normalizeEmailChangeInput: context.normalizeEmailChangeInput,
    normalizeLoginInput: context.normalizeLoginInput,
    normalizeOeCustomisationImageFolder:
      context.normalizeOeCustomisationImageFolder,
    normalizeOeCustomisationStatus: context.normalizeOeCustomisationStatus,
    normalizeOeIcon: context.normalizeOeIcon,
    normalizeCustomisationPreferences:
      context.normalizeCustomisationPreferences,
    normalizePrivacySettings: context.normalizePrivacySettings,
    normalizePackHexColour: context.normalizePackHexColour,
    normalizePasswordResetInput: context.normalizePasswordResetInput,
    normalizePasswordResetRequestInput:
      context.normalizePasswordResetRequestInput,
    normalizeReportText: context.normalizeReportText,
    parseAppleUserPayload: context.parseAppleUserPayload,
    parseBooleanLabel: context.parseBooleanLabel,
    parseCompositePartyContentKey: context.parseCompositePartyContentKey,
    parseNullableNumber: context.parseNullableNumber,
    parseOAuthCookie: context.parseOAuthCookie,
    parseOAuthState: context.parseOAuthState,
    parseOverexposurePostedAt: context.parseOverexposurePostedAt,
    parseRestrictionList: context.parseRestrictionList,
    canAccessFeature: context.canAccessFeature,
    requireOePanelAccount: context.requireOePanelAccount,
    requireFeatureAccess: context.requireFeatureAccess,
    requireOePanelPermission: context.requireOePanelPermission,
    requireVerifiedAccount: context.requireVerifiedAccount,
    reserveSocialUsername: context.reserveSocialUsername,
    recordFailedLogin: context.recordFailedLogin,
    saveOeCustomisationSvgUpload: context.saveOeCustomisationSvgUpload,
    serializeAccount: context.serializeAccount,
    serializeActiveRoom: context.serializeActiveRoom,
    serializeArchivedRoom: context.serializeArchivedRoom,
    serializeGamemodeSettingsAlert: context.serializeGamemodeSettingsAlert,
    serializeOAuthCookie: context.serializeOAuthCookie,
    serializeOeCustomisationImageForPanel:
      context.serializeOeCustomisationImageForPanel,
    serializeOeCustomisationPackForPanel:
      context.serializeOeCustomisationPackForPanel,
    serializeOePanelModerationReport: context.serializeOePanelModerationReport,
    serializeOePanelOverexposureReport:
      context.serializeOePanelOverexposureReport,
    serializeOePanelUser: context.serializeOePanelUser,
    serializeOverexposurePost: context.serializeOverexposurePost,
    serializePartyPackForPanel: context.serializePartyPackForPanel,
    serializePartyRoleForPanel: context.serializePartyRoleForPanel,
    serializePartyRuleForPanel: context.serializePartyRuleForPanel,
    serializeProductMedia: context.serializeProductMedia,
    serializeRoomErrors: context.serializeRoomErrors,
    serializeShopProduct: context.serializeShopProduct,
    serializeShopVariant: context.serializeShopVariant,
    slugifyOeCustomisationFileName: context.slugifyOeCustomisationFileName,
    spendOpalsForProduct: context.spendOpalsForProduct,
    upgradeGuestPartyIdentityForAccount:
      context.upgradeGuestPartyIdentityForAccount,
    validateAccountOeIconAccess: context.validateAccountOeIconAccess,
    toPlainObject: context.toPlainObject,
    validateAccountInput: context.validateAccountInput,
    validateEmailChangeInput: context.validateEmailChangeInput,
    validateLoginInput: context.validateLoginInput,
    validateOeCustomisationSvgDimensions:
      context.validateOeCustomisationSvgDimensions,
    validatePasswordResetInput: context.validatePasswordResetInput,
    validatePasswordResetRequestInput: context.validatePasswordResetRequestInput
  };
}

module.exports = { createPublicApiRouteContext };
